### ISSUE TITLE
BUG: Export to SQL format problem with array and json types

### ISSUE THREAD

**Issue by mojtabakaviani** [beekeeper-studio/beekeeper-studio#1223]
For example data in array column

```
[4,16,10,15,2,7]
```
output is

```
 '{"0":4,"1":16,"2":10,"3":15,"4":2,"5":7}'
```

or for json type
```
{"keys":[9,11]}
```
convert array to object with unknown characters "0": and  "1":
```
'{"keys":{"0":9,"1":11}}'
```
correct output is

```
'{"keys":[9,11]}'
```

also for empty array or json output is

```
'{}' or '{"0"}'
```

**Comment by mojtabakaviani** [comment]
table with array columns
![image](https://user-images.githubusercontent.com/1667525/169114171-583f7596-f518-4a9a-9d9f-9f32cd3fd320.png)

```sql
insert into "plans" ("axis", "creators", "filters", "id", "is_active", "is_activity", "is_attach", "is_comment", "is_expand", "is_labeling", "is_remember", "is_search", "is_telegram", "is_whatsapp", "name", "repeat", "viewers", "wages") values (2, '{"0":12,"1":28,"2":18,"3":17}', NULL, 13, true, true, true, true, false, false, true, false, false, false, 'translate', 2, '{"0":12,"1":28,"2":18,"3":17}', '{"0":30000,"1":0,"2":0,"3":0,"4":0,"5":0,"6":0}');
```
table with array and json columns
![image](https://user-images.githubusercontent.com/1667525/169115588-015bc925-f0bc-495a-b72a-f3a5d5e59d6a.png)

```sql
insert into "task_step_answers" ("answer", "answers", "content", "created_at", "creator_id", "question_id", "step_id", "task_id") values ('{"keys":{"0":58,"1":59,"2":60,"3":61,"4":62,"5":63}}', '{"0":58,"1":59,"2":60,"3":61,"4":62,"5":63}', NULL, '2021-09-12 14:46:16.624809', 38, 15, 98, 1633);
```

**Comment by mojtabakaviani** [comment]
Problem not solved!

**Comment by rathboma** [comment]
Oh... I think the json columns might still be broken. Let me check. Arrays are fixed though

**Comment by mojtabakaviani** [comment]
I has checked, array and json columns not fixed. also array column render as json object.
