### ISSUE TITLE
BUG: Complete gray screen

### ISSUE THREAD

**Issue by vitorwlima** [beekeeper-studio/beekeeper-studio#2325]
**Describe the bug**
I clicked on File -> "Import SQL Files" and selected a large file of 165MB (I was trying to restore a DB backup). After that, the app turned completely gray and I can't use it anymore. I tried uninstalling the app to install it again, closing it, and restarting my MacBook. It's unusable now, and I don't know how that happened.

My theory is that the file is too big and being loaded every time but that doesn't make sense. If that's correct - can anyone tell me the path I need to delete so that I can go back to using Beekeeper?

**To Reproduce**
1. Go to File -> "Import SQL Files"
2. Select a large file
3. Watch your app stop working forever

**Expected behavior**

**Screenshots / Gifs**
![image](https://github.com/user-attachments/assets/3aafee18-e123-4746-931f-e832511021b7)

**Version Information (please complete the following information):**
 - OS: Macbook M1
 - App Version: 4.6.4 (4.6.4)

**Additional context**
I really appreciate it if there is a quick way for me to fix it, I use the software daily and I'm unable to do so now.

**Comment by not-night-but** [comment]
@vitorwlima Sorry you're having this issue, are there any errors in the console?

**Comment by vitorwlima** [comment]
@not-night-but 
Dev tools do not seem to be working - it's like the page is completely off.

![image](https://github.com/user-attachments/assets/ceb6008e-06e1-4205-ae66-2432b9a46517)

**Comment by not-night-but** [comment]
In terms of getting that import working, @wmontgomery has been working on upgrading our import process so that it can actually handle these larger files and doesn't just load the entire thing into memory

**Comment by not-night-but** [comment]
I mean db as in the sqlite db that we use for app settings, storing connections, etc. But the fact that you can load the main screen means that isn't an issue. Try Help -> Add Beekeeper's Database and see if you can connect to the app database (should be called `Beekeeper's Database`)

**Comment by vitorwlima** [comment]
I can do that, check it out:

https://app.usebubbles.com/vmBqmZFqf8PiQeTpfT2Xcp/beekeeper

**Comment by not-night-but** [comment]
Okay that's incredibly frustrating :upside_down_face: . I think we should try generating a new appdb. So I'd move the file that `Beekeeper's Database` is pointing to to some other directory (Downloads or whatever). The app should regenerate the appdb file, and with that we should hopefully be able to connect again? 

This is the file I'm talking about: 
![image](https://github.com/user-attachments/assets/a62c7faf-7a2b-421d-ab0f-6eac80e37d4e)

Don't delete it, just move it elsewhere. Ideally you should be able to connect to it later to get your connections back

**Comment by vitorwlima** [comment]
@not-night-but that works! It reset my app completely but I can work now at least with some setup, thanks.

**Comment by not-night-but** [comment]
Okay that's good at least!!! I'd be very interested to see what's in that database that has caused such issues. My guess is that when the app crashed initially, that crashed state was set on the import tab and then the app just kept trying to reload that. @wmontgomery may be something to look into? We at least have a workaround now, but I'm not comfortable just leaving this floating around in the wild

**Comment by bookchiq** [comment]
I ran into this as well. I tried importing a large SQL file, the app greyed out, and restarting the app and trying to use any connection (not just the one I'd been using) greyed out the app again. No developer tools connected. Same behavior after redownloading/reinstalling.

I'm on a Mac, and the app.db file is located at `~/Library/Application Support/beekeeper-studio/app.db` (mentioning for future googlers). Relocating the file resulted in a new, unbroken one being generated. I needed to re-add my connections but it works again.

@not-night-but I'd be happy to send you the problem app.db file privately (it has some medium-sensitive data in it) if you want to poke at it.

**Comment by not-night-but** [comment]
@bookchiq that would be lovely!!! You can send it to me on the community slack if you're on there, or to the email on my profile

**Comment by MaxLmqr** [comment]
Hello, same issue here. As a workaround to make it work without losing all saved connections, I opened the app.db and deleted a line from the `favorite_query` table. Hope this can help.

**Comment by rathboma** [comment]
I think this issue here is that `import sql files` is not for database RESTORE, it's for importing .sql files into the app database as saved queries. That's def the confusion here. If you'd used tools -> Restore database, this would likely have worked fine.

@not-night-but this is nothing to do with importing data -- it's with importing .sql files into the `favorite_query` table

**Comment by rathboma** [comment]
I think we should do some better wording here in the app

**Comment by 021-projects** [comment]
> I think this issue here is that `import sql files` is not for database RESTORE, it's for importing .sql files into the app database as saved queries. That's def the confusion here. If you'd used tools -> Restore database, this would likely have worked fine.
> 
> [@not-night-but](https://github.com/not-night-but) this is nothing to do with importing data -- it's with importing .sql files into the `favorite_query` table

You caught me, hahah)

**Comment by Stefan2142** [comment]
Same issue here. Same steps, tried importing ~500mb .sql file. It stopped responding, cmd +q. Then, tried opening it again and then I started facing the same issue as the OP above. Tried restarting the postgresql server manually and tried restarting/turning of the macbook and still the same issue. Nothing helps. Any ideas? Shame that Beekeeper asks for a premium price on their software and support is nowhere to be found especially on a ticket thats a month old.

Macos 15.6, beekeeper 5.3.4

**Comment by martijnvdbrug** [comment]
> Same issue here. Same steps, tried importing ~500mb .sql file. It stopped responding, cmd +q. Then, tried opening it again and then I started facing the same issue as the OP above. Tried restarting the postgresql server manually and tried restarting/turning of the macbook and still the same issue. Nothing helps. Any ideas? Shame that Beekeeper asks for a premium price on their software and support is nowhere to be found especially on a ticket thats a month old.

I had the exact same scenario, but as stated in the comments above, this probably corrupted the `app.db`. When you delete it, it works again.

It would be nice to have connection settings (without passwords) in a separate config file, for portability.

**Comment by Ahellrigel33** [comment]
I had this exact same scenario. Per @MaxLmqr, I was able to navigate to `~/Library/Application Support/beekeeper-studio` and run the following command:

```
sqlite3 -header -column app.db "SELECT id, title, LENGTH(text) as text_length FROM favorite_query;"
```

This revealed an entry with a very long text length. I assume beekeeper was trying to load this sql query when opening which was causing the crash.

I simply ran:

```
sqlite3 app.db "DELETE FROM favorite_query WHERE id = 22;"
```

(22 was the problematic entry for me, but obviously change this number depending on the results of your query) and this fixed my issue.

**Comment by vitorwlima** [comment]
Closing this one. The fix is deleting `app.db` file or the corrupted record inside of it. For whoever needs it, you can get more info by reading the whole thread 🫡

**Comment by not-night-but** [comment]
Just so everyone in this thread is aware, we have merged a fix for this as well. Basically we've revamped how queries are loaded in app so this shouldn't happen ever again

**Comment by amcgready** [comment]
I just wanted to add that the problem is still persisting with this issue. I had a larger SQL file that I had imported and ran a query on that caused a corruption with the `app.db`. Deleting that file allowed me to setup and connect again. So larger queries are still not being handled properly it seems.
