### ISSUE TITLE
BUG: DuckDB connection not releasing lock

### ISSUE THREAD

**Issue by paul-schwendenman** [beekeeper-studio/beekeeper-studio#3010]
**Describe the bug**
DuckDB connection not closed on disconnect / lock not released

**To Reproduce**
1. Connect to a DuckDB database
2. Click on disconnect
3. Attempt to connect to the same DB with another tool
4. See error: "IO Error: Could not set lock on file "

**Expected behavior**
The lock on the file should be released when "disconnect" is selected

**Screenshots / Gifs**

<img width="297" alt="Image" src="https://github.com/user-attachments/assets/85d08cfd-9651-44a1-a7fe-b2d4daa3597b" />

```
duckdb.duckdb.IOException: IO Error: Could not set lock on file "/path/to/my.duckdb": Conflicting lock is held in /Applications/Beekeeper Studio.app/Contents/Frameworks/Beekeeper Studio Helper.app/Contents/MacOS/Beekeeper Studio Helper (PID 84821) by user paul. However, you would be able to open this database in read-only mode, e.g. by using the -readonly parameter in the CLI. See also https://duckdb.org/docs/connect/concurrency
```

and 

```
duckdb.duckdb.IOException: IO Error: Could not set lock on file "/path/to/my.duckdb": Conflicting lock is held in /Applications/Beekeeper Studio.app/Contents/Frameworks/Beekeeper Studio Helper.app/Contents/MacOS/Beekeeper Studio Helper (PID 84821) by user paul. See also https://duckdb.org/docs/connect/concurrency
```

**Version Information (please complete the following information):**
 - OS: Mac 14.6.1 (23G93)
 - App Version 5.1.5
 - Database type and version duckdb

**Additional context**
You can close the app to release the lock, but that's obviously not an ideal workflow

**Comment by dcharlesv** [comment]
Same issue with DuckDB and VS Code - Have to shutdown Beekeper to remove the table lock, as Disconnect not unlocking.
Mac M2 Pro Sequoia 15.4 - latest Duckdb - App 5.1.5

**Comment by azmy60** [comment]
I'll try to address this next week.

**Comment by azmy60** [comment]
Just a friendly heads up. We have fixed this in the latest version. Please let us know if you still find the issue!

**Comment by paul-schwendenman** [comment]
Is `5.2.12` a version with the fix? I was still able to recreate the issue. I selected "Check for software updates" but there wasn't any visual feedback. But that seems to be the latest version in github

I am able to recreate the issue on 5.2.12 with the following steps:

1. Created a new db

```
$ duckdb test.db <<EOF
CREATE TABLE my_table (
    id INTEGER,
    name TEXT
);
EOF
```

2. checked i could connect

```
$ duckdb test.db <<< "DESCRIBE my_table;"
┌─────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│ column_name │ column_type │  null   │   key   │ default │  extra  │
│   varchar   │   varchar   │ varchar │ varchar │ varchar │ varchar │
├─────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ id          │ INTEGER     │ YES     │ NULL    │ NULL    │ NULL    │
│ name        │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
└─────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘
```

3. open with beekeeper

4. disconnect beekeeper

5. check in terminal

```
$ duckdb test.db <<< "DESCRIBE my_table;"
Error: unable to open database "test.db": IO Error: Could not set lock on file "test.db": Conflicting lock is held in /Applications/Beekeeper Studio.app/Contents/Frameworks/Beekeeper Studio Helper.app/Contents/MacOS/Beekeeper Studio Helper (PID 11730) by user paul. See also https://duckdb.org/docs/connect/concurrency
```

6. quit beekeeper

7. check again

```
$ duckdb test.db <<< "DESCRIBE my_table;"
┌─────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│ column_name │ column_type │  null   │   key   │ default │  extra  │
│   varchar   │   varchar   │ varchar │ varchar │ varchar │ varchar │
├─────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ id          │ INTEGER     │ YES     │ NULL    │ NULL    │ NULL    │
│ name        │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
└─────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘
```

**Comment by dcharlesv** [comment]
Same here... 5.2.12 still not releasing duckdb lock on disconnect - only quitting the entire app releases.

**Comment by not-night-but** [comment]
@azmy60 can you look into this?

**Comment by not-night-but** [comment]
@dcharlesv @paul-schwendenman I just tested the PR that's linked to this issue with your repro steps, and it seems the issue has been fixed! It's in master now, so it will be out with the next release. So sorry for the mixup with this

**Comment by paul-schwendenman** [comment]
Ok, my desktop client just offered an update and I can confirm this appears to be fixed in version `5.3.1` which appears to have been released for the Mac today(?)

Thanks!
