### ISSUE TITLE
How to connect it to the server after first installation ?

### ISSUE THREAD

**Issue by Nova-Striker** [beekeeper-studio/beekeeper-studio#405]
**Details:**
I am trying to connect to mysql server (PORT 3306) . But I am getting an error : 
` server requests authentication using unknown plugin sha256_password. See TODO: add plugins doco here on how to configure or author authentication plugins .`

**Version Information [might be relevant to your issue]**
Operating System: Linux (Ubuntu 20.04)
App Version [help -> about]: 1.8.2
mysql  Ver 8.0.21 for Linux on x86_64 (MySQL Community Server - GPL)

**Screenshot / GIF [if appropriate]**:
![Screenshot from 2020-10-24 00-02-30](https://user-images.githubusercontent.com/64089730/97040876-414b7100-158c-11eb-83c1-f869f4422f26.png)

**Comment by rathboma** [comment]
I'm guessing you're using mysql 8?

Yeah we've seen this problem before. It's because MySQL 8 makes a whole bunch of changes that are not backwards compatible.

A workaround it so change how your password is stored in the database:

```sql
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';
flush privileges;
```
Then try connecting again.

Also - try connecting without `@localhost` in your username, you should be able to connect with `root`

**Comment by rathboma** [comment]
Oh, this might just be your username. Try just `root` and see if it works?

**Comment by rathboma** [comment]
From reading more, it looks like you might be using a slightly out of date version of MySQL 8. Let me know if changing your username works.

Looks like `sha256_password` was deprecated in favor of `caching_sha2_password`, and support for `sha256_password` was dropped from MySQL clients. So that's the cause of the problem.

**Comment by Nova-Striker** [comment]
**Setting the username to `root` didn't help me at first**

---

![Screenshot from 2020-10-24 11-59-17](https://user-images.githubusercontent.com/64089730/97070505-7b515d00-15f6-11eb-918f-d09b95456369.png)

---

**But then I check the Authentication Plugin used by `root` and found that it was set to `auth_socket`**
Command : 
`show create user root@localhost;`

![Screenshot from 2020-10-24 12-42-31](https://user-images.githubusercontent.com/64089730/97070527-a2a82a00-15f6-11eb-8030-5dc30c8cce12.png)
 
-----

So , I changed the authentication type using the following command : 

`ALTER USER 'root'@'localhost' IDENTIFIED WITH caching_sha2_password BY '<new password>';`
`FLUSH PRIVILEGES;`

**After that , using the username as `root` and entering the password established my connection with the server.**

----

**P.S : Before doing the above steps , I upgraded Mysql to version 8.0.22**

**Comment by subnut** [comment]
Just FYI, it is never advisable to change the default `auth_socket` authentication for the `root` user (for security purposes).
Also, the `root` user should not be used for normal access, always create a separate user for that.

cc @rathboma @Nova-Striker

**Comment by rathboma** [comment]
Yes it was just an example. Apologies if that was confusing.

This problem is fixed in master anyway, so it'll work with either encryption algorithm as of the next release.

I'll put together a minor point release next week with this and other minor fixes.

Matthew

**Comment by johannsa** [comment]
FYI, @rathbona, authentication with auth_socket is still failing in 1.8.11 with "Access denied for user 'root'@'localhost'".
I am connecting to MySQL 8.0.22 on Debian from Beekeeper Studio for Windows.

**Comment by subnut** [comment]
@johannsa If you can login from the console, then please do login from the console and make a separate user dedicated for BeeKeeper Studio. Then try again with the new username. It _should_ work.

**Comment by rathboma** [comment]
That seems like a separate issue. Is mysql running in wsl by any chance?
