### ISSUE TITLE
FEAT: Allow for user without password

### ISSUE THREAD

**Issue by DGollings** [beekeeper-studio/beekeeper-studio#499]
**Is your feature request related to a problem? Please describe.**
Related to #498, allow for a passwordless user.
Cockroachdb defaults to a TLS connection where user root has no password (as there's a TLS keyfile required/supplied)

**Describe the solution you'd like**
Don't attempt to use a password if the user doesn't supply a password

**Describe alternatives you've considered**
Luckily already had an admin user with a password, but supporting the default CRDB connection also seems like a good idea

**Comment by rathboma** [comment]
Thanks! Seems reasonable.

**Comment by rathboma** [comment]
Should be fixed in master

**Comment by DGollings** [comment]
Still getting a password authentication failed for user root? Also don't see anything related to this in git log

**Comment by rathboma** [comment]
Hmm can you confirm that logging in without a password through another app works?

**Comment by DGollings** [comment]
any other app? DBeaver works

I also had to modify some go library (sqlboiler I believe) to allow this behaviour, generally its possible

```
kubectl exec -it cockroachdb-client-secure \
-- ./cockroach sql \
--certs-dir=/cockroach-certs \
--host=cockroachdb-public
```

This is for example how I can connect a CLI sql client, the `-user root` is implicit, but there's definitely no password.

Do you have an instance of Kubernetes laying around? It's quite easy to start a secure cluster, could send some commands if you like

**Comment by rathboma** [comment]
Ok, I'll debug the issue this week. Things that would help:
1. Screenshot of how you configure another client (eg DBeaver)
2. Screenshot of the error, and configuration in Beekeeper Studio
3. Any other information you think is important

**Comment by DGollings** [comment]
Not that I mind making screenshots, but it would be mostly empty or very basic fields. 

**Common settings**
Host: localhost
Port: 26257
Username: root
Database: *dbname*

Both have 'save password locally' enabled
Both have SSL configured (.cer vs .pk8, but I doubt that's relevant)

**Diff**
The only thing that is slightly different is that DBeaver has the following option:
Authentication: with options 'Database Native' and 'PgPass'

**Comment by DGollings** [comment]
As mentioned, I once had to change some go code in some code generation library to support this. Although I now see I didn't have to fix the 'skip password if no password part' 
My guess is that either your code or the underlying library doesnt do the following:

```
buildQueryString(user, pass, dbname, host string, port int, sslmode string) string {
	var up string
	if user != "" {
		up = user
	}
	if pass != "" {
		up = fmt.Sprintf("%s:%s", up, pass)
	}
	return fmt.Sprintf("postgresql://%s@%s:%d/%s?sslmode=%s", up, host, port, dbname, sslmode)
```

which is used like this:
```
d.connStr = buildQueryString(user, pass, dbname, host, port, sslmode)
d.conn, err = sql.Open("postgres", d.connStr)
```

Where the relevant part being that username:password@host or username@host is determined using `if user != "" && pass != ""` and formatted into var `up`

**Comment by rathboma** [comment]
So this might be a limitation with the postgres driver I'm using. I'm specifically not using the native postgres library, but instead using the nodejs implementation, so this might be a problem with that, because it doesn't use the connection URL.

I'll make a branch using the native version, and ping you to try testing it!

**Comment by DGollings** [comment]
which driver do you use? because I just enabed SQLTools in vscode, using 
`https://node-postgres.com/api/pool`
`Passed directly to node.TLSSocket. Check more here: https://nodejs.org/api/tls.html#tls_new_tls_tlssocket_socket_options`
(copied straight from config page)

and there's the option:
"Use password" : "Use empty password"

I think there's a decent chance you're using the same driver in which case reading the code might help you debug this faster

**Comment by Madeindreams** [comment]
Having the same issue.

I have one container that runs CRDB.

Parse a config file to get my DB settings.

With NodeJS

```
DatabaseSettings:
  database: "wall_signatures"
  driver: "cockroachdb"
  host: "localhost"
  port: "26257"
  user: "idfi_app"
  pass: ""
  ssl: false
```
This is working fine


with golang

```
DatabaseSettings:
  Database: "operator"
  Driver: "cockroachdb"
  Host: "localhost"
  Port: "26257"
  User: "operator_app"
  Password: ""
  SSLModeDisable: true

```
Fail to connect with this error.

`pq: password authentication failed for user username`

**Comment by Madeindreams** [comment]
Turns out that with nodeJS

`cockroach sql --accept-sql-without-tls` flag will let you connect without a password.


To be able to connect with golang without a password I have to use the `--insecure` flag.

Note that in both case I have disabled SSL since I'm working locally

**Comment by Madeindreams** [comment]
Also worth mentioning that the behaviour is not the same on Linux and Windows machine. Even tho they are dockerized!?
