### ISSUE TITLE
BUG: Context menu SQL: Create table missing semicolom (;)

### ISSUE THREAD

**Issue by gnovaro** [beekeeper-studio/beekeeper-studio#521]
**Describe the bug**
When you click on a table with right button on context menu, beekeeper generate the SQL for CREATE TABLE on the editor but not add ";" in the end off the script

**To Reproduce**
1. In the "Entitites" left bar choose a table
2. Right Click on the table and click on "SQL: Create table"
3. See the error in the editor

**Expected behavior**
Add missing ; to the end off the SQL script

**Screenshots / Gifs**
![Captura de pantalla de 2021-01-22 11-29-00](https://user-images.githubusercontent.com/270990/105481014-be2ed980-5ca6-11eb-80b0-8629fb61acd1.png)

**Version Information (please complete the following information):**
1.9.1

 - OS: Ubuntu
 - App Version [e.g. help -> About Beekeeper Studio]

**Additional context**
----

**Comment by rathboma** [comment]
I think this is fixed.

**Comment by gnovaro** [comment]
The problem still persist.

![image](https://user-images.githubusercontent.com/270990/178953834-b0e89ce5-5abc-4219-b5ac-e12672e21b75.png)
