### ISSUE TITLE
BUG: Unable to run master branch

### ISSUE THREAD

**Issue by geovannimp** [beekeeper-studio/beekeeper-studio#528]
**Describe the bug**
Unable to run master branch

**To Reproduce**
1. Clone branch
2. Run `yarn install`
3. Run `yarn electron:serve`
4. App opens but empty
5. The following error is shown in terminal:

```
Failed to read /index.html on app protocol [Error: ENOENT: no such file or directory, open '/home/geovanni/Programacao/Projetos/temp/beekeeper-studio/dist_electron/index.html'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/geovanni/Programacao/Projetos/temp/beekeeper-studio/dist_electron/index.html'
}
```

**Expected behavior**
The app should open in development mode

**Screenshots / Gifs**
![Peek 27-01-2021 06-03](https://user-images.githubusercontent.com/4943174/105968214-8d172600-6065-11eb-9760-5036b368f2dc.gif)
![image](https://user-images.githubusercontent.com/4943174/105968431-d8313900-6065-11eb-83ab-1ce04c4b6061.png)

**Version Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - App Version: master

**Comment by rathboma** [comment]
That should be fixed already :-)

**Comment by geovannimp** [comment]
I'm running last master version, commit `81a639fd8448619b2fb9aa57e3044bd133c713c2` and still having this issue

**Comment by fabscav** [comment]
I'm having the same issue. Seems to stem from 97fb562e8023c16f8fbf83b4892bf3472ffd8f7f.

If I modify `src/background/WindowBuilder.ts` and change
```
runningInWebpack: !!p.env.WEBPACK_DEV_SERVER_URL,
appUrl: p.env.WEBPACK_DEV_SERVER_URL ? p.env.WEBPACK_DEV_SERVER_URL : 'app://./index.html'
```
to
```
runningInWebpack: !!process.env.WEBPACK_DEV_SERVER_URL,
appUrl: process.env.WEBPACK_DEV_SERVER_URL ? process.env.WEBPACK_DEV_SERVER_URL : 'app://./index.html'
```
I can build again.

**Comment by rathboma** [comment]
I realized I fixed this in a branch that I then threw away (doh), so re-applied the changes.
