### ISSUE TITLE
BUG: "Devtools was disconnected from the page" when debugging on Windows

### ISSUE THREAD

**Issue by yogaxpto** [beekeeper-studio/beekeeper-studio#546]
**Describe the bug**
When running "electron:serve" the renderer process crashes on application start.

**To Reproduce**
1. Follow the installation guide
2. run "yarn run electron:serve"

**Expected behavior**
The program to run

**Screenshots / Gifs**
I've also added `--enable-logging` and got some more information, which is included in the [log.txt](https://github.com/beekeeper-studio/beekeeper-studio/files/5944978/log.txt) file

**Version Information (please complete the following information):**
 - OS: Windows 10
 - App Version: latest version in master branch

**Comment by rathboma** [comment]
I think this may have been electron 11 issue, I just pushed a re-downgrade to electron 9, can you try again?

Not sure what that log output is all about.

**Comment by yogaxpto** [comment]
The problem persists after commit #ff0715381b1139008aa539b31322174e8960b961 

I must also add that the node version is 15.8.0 and yarn is 1.22.10

**Comment by rathboma** [comment]
So we have this fixed in a branch for the initial load, but it's still a problem across all platforms when hot-reloading changes.

Not sure why, filed some issues with some of the toolchain projects we use, hopefully some fixes come through

**Comment by yogaxpto** [comment]
What is the name of the branch? May I test that fix?

**Comment by yogaxpto** [comment]
Closed as stale.
