### ISSUE TITLE
BUG: Filters crash and using _ in entities filters does not work for when result are functions only

### ISSUE THREAD

**Issue by tvarsis** [beekeeper-studio/beekeeper-studio#825]
When adding _ to a filter, then it shows a matching number in the entities, but no actual entities are shown in the list.

![image](https://user-images.githubusercontent.com/10090010/135402890-ce948a45-68e7-4e20-8e1b-fb9ccd41892a.png)

Adding the _ to the filter which should match as seen in picture one, clears the list, but the numbers of filtered entities goes from 43 to 42. So the filter seems to be applied, only the list goes blank instead of showing them. No errors in console etc. This seems to only happen when the filters ends up matching functions only in the list:
![image](https://user-images.githubusercontent.com/10090010/135402961-8df4f97c-962f-4451-a94f-1aa5dfca6ab6.png)

Playing around with the filters more, it seems to pretty often crash as well with this error which is probably unrelated to the _ issue, which requires a restart of Beekeeper for the entities list to start working again:
![image](https://user-images.githubusercontent.com/10090010/135403670-e99e889f-9983-4c98-a440-7e540fecbfc9.png)

 - OS: OpenSUSE Tumbleweed
 - App Version: 2.1.4 Appimage

**Comment by rathboma** [comment]
This is fixed!

**Comment by tvarsis** [comment]
@rathboma Still seeing this error which filtering on _in leads to (last error in picture). After that Beekeeper pretty much stops working (can't open tables etc) until I restart it:

![image](https://user-images.githubusercontent.com/10090010/166110401-29ea63e3-0f38-4023-a6c2-638663362f9a.png)

Version 3.4.2

**Comment by tvarsis** [comment]
@rathboma This issue should be reopened unless the fix is unreleased, which I doubt. Still exists as of 3.4.2
